# Generated by Django 4.2.7 on 2023-11-21 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='film-resimleri')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('price', models.IntegerField(max_length=12)),
                ('slug', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
