# Generated by Django 4.2.7 on 2023-11-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otel',
        ),
    ]
