# Generated by Django 4.2.7 on 2023-11-22 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0002_delete_otel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('adres', models.CharField(default='bir adres', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='hotel_images')),
                ('rating', models.CharField(max_length=5)),
                ('map', models.CharField(max_length=10000)),
                ('review_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('tax', models.CharField(max_length=20)),
                ('cancel', models.CharField(max_length=25)),
                ('room', models.CharField(max_length=500)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
