# Generated by Django 4.2.7 on 2023-11-29 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.FileField(null=True, upload_to='hotels_images')),
                ('adress', models.CharField(max_length=50)),
                ('review_count', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=10)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='otel',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='otel',
            name='tax',
            field=models.CharField(max_length=50),
        ),
    ]
