# Generated by Django 4.2.7 on 2023-11-28 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtelEkle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='hotel_images')),
                ('title', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
                ('derece', models.CharField(max_length=50)),
                ('degerlendirmne', models.CharField(max_length=50)),
                ('fiyat', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='otel',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='otel',
            name='tax',
            field=models.CharField(max_length=50),
        ),
    ]
