# Generated by Django 4.2.5 on 2023-11-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otel',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='otel',
            name='tax',
            field=models.CharField(max_length=50),
        ),
    ]
