# Generated by Django 4.2.7 on 2023-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_tesis_alter_otel_price_alter_otel_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
