# Generated by Django 4.2.7 on 2023-11-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_otel_price_alter_otel_tax'),
        ('movie', '0004_otelekle_alter_otel_price_alter_otel_tax'),
        ('movie', '0005_alter_tesis_title'),
    ]

    operations = [
    ]
