# Generated by Django 4.2.7 on 2023-11-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_merge_20231130_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtelEkle',
        ),
        migrations.AlterField(
            model_name='otel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
