# Generated by Django 4.2.7 on 2023-12-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_delete_otelekle_alter_otel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otel',
            name='image',
            field=models.ImageField(null=True, upload_to='tesis_images'),
        ),
    ]
